# -*- coding: utf-8 -*-
#
# Copyright (c) 2011 -- Lars Heuer <heuer[at]semagia.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
#     * Neither the project name nor the names of the contributors may be 
#       used to endorse or promote products derived from this software 
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
"""\
This module provides some global constants.

:author:       Lars Heuer (heuer[at]semagia.com)
:organization: Semagia - <http://www.semagia.com/>
:license:      BSD license
"""
import re

# Min/max length of station identifiers
MIN_ORIGIN_LENGTH = len(u'ROME')
MAX_ORIGIN_LENGTH = len(u'BANDARSERIBEGAWAN')

# Reference kind constants
REF_KIND_UNKNOWN = 0
REF_KIND_CABLE = 1
REF_KIND_EMAIL = 2
REF_KIND_BOOK = 3
REF_KIND_TEL = 4
REF_KIND_REPORT = 5
REF_KIND_FAX = 6

# Min/max cable serial number length
MIN_SERIAL_LENGTH = 1
MAX_SERIAL_LENGTH = 7

# Valid station identifiers
_STATIONS = (
    # A
    'ABIDJAN', 'ABUDHABI', 'ABUJA', 'ACCRA', 'ADDISABABA', 
    'AITTAIPEI', 'ALGIERS', 'AMMAN', 'AMSTERDAM', 'ANKARA', 
    'ASHGABAT', 'ASMARA', 'ASTANA', 'ASUNCION', 'ATHENS',
    'ADANA', 'ALMATY', 'APIA', 'AUCKLAND', u'ANTANANARIVO',
    u'ALEXANDRIA',
    # B
    'BAGHDAD', 'BAKU', 'BAMAKO', 'BANDARSERIBEGAWAN', 'BANGKOK', 
    'BANJUL', 'BARCELONA', 'BASRAH', 'BEIJING', 'BEIRUT', 
    'BELGRADE', 'BERLIN', 'BERN', 'BISHKEK', 'BOGOTA', 
    'BRASILIA', 'BRATISLAVA', 'BRIDGETOWN', 'BRUSSELS', 'BUCHAREST', 
    'BUDAPEST', 'BUENOSAIRES', 'BUJUMBURA', 'BRAZZAVILLE', 'BELIZE',
    'BELFAST', u'BELMOPAN', u'BONN', u'BANGUI',
    # C
    'CAIRO', 'CALCUTTA', 'CANBERRA', 'CAPETOWN', 'CARACAS', 
    'CASABLANCA', 'CHENNAI', 'CHISINAU', 'CIUDADJUAREZ', 'COLOMBO', 
    'CONAKRY', 'COPENHAGEN', 'CURACAO', 'CALGARY', 'CHIANGMAI',
    u'CHENGDU', u'COTONOU', u'CDGENEVA',
    'CDCATLANTAGA', # found in cable refs "Centers for Disease Control and Prevention"
    # D
    'DAKAR', 'DAMASCUS', 'DARESSALAAM', 'DHAKA', 'DJIBOUTI', 
    'DOHA', 'DUBAI', 'DUBLIN', 'DUSHANBE', 'DHAHRAN', 'DILI',
    u'DURBAN', u'DAMASCCUS',
    'DUSSELDORF', # found in cable refs
    # F
    'FREETOWN', 'FUKUOKA', u'FSINFATC',
    'FRANKFURT', # Found in cable refs
    # G
    'GABORONE', 'GENEVA', 'GUATEMALA', 'GUADALAJARA', 'GUAYAQUIL',
    'GUANGZHOU', u'GEORGETOWN', u'GRENADA',
    # H
    'HAMBURG', 'HANOI', 'HARARE', 'HAVANA', 'HAMILTON', 'HELSINKI', 'HERMOSILLO',
    'HALIFAX', 'HOCHIMINHCITY', 'HONGKONG', u'HILLAH',
    # I
    'IRANRPODUBAI', 'ISLAMABAD', 'ISTANBUL', u'IZMIR',
    # J
    'JEDDAH', 'JERUSALEM', u'JAKARTA', u'JOHANNESBURG',
    # K
    'KABUL', 'KAMPALA', 'KATHMANDU', 'KHARTOUM', 'KIEV', 'KIGALI', 
    'KINSHASA', 'KUALALUMPUR', 'KUWAIT', 'KYIV', 'KOLKATA', 'KINGSTON',
    'KARACHI', u'KRAKOW', u'KOLONIA',
    # L
    'LAGOS', 'LAPAZ', 'LAHORE', 'LILONGWE', 'LIMA', 'LISBON', 'LJUBLJANA',
    'LONDON', 'LUANDA', 'LUXEMBOURG', 'LIBREVILLE', u'LUSAKA', u'LEIPZIG',
    'LOME', # Found in cable refs
    # M
    'MALABO', 'MADRID', 'MANAGUA', 'MANAMA', 'MAPUTO', 'MBABANE', 'MEXICO', 
    'MILAN', 'MINSK', 'MONROVIA', 'MONTERREY', 'MONTEVIDEO', 'MONTREAL', 
    'MOSCOW', 'MUMBAI', 'MUNICH', 'MUSCAT', 'MELBOURNE', 'MANILA',
    'MATAMOROS', 'MASERU', u'MOGADISHU', u'MARSEILLE', u'MERIDA',
    # N
    'NAIROBI', 'NAPLES', 'NASSAU', 'NEWDELHI', 'NIAMEY', 'NICOSIA',
    'NDJAMENA', 'NAHA', 'NUEVOLAREDO', 'NAGOYA', u'NOUAKCHOTT',
    # O 
    'OSLO', 'OTTAWA', 'OUAGADOUGOU', 
    # P
    'PANAMA', 'PARAMARIBO', 'PARIS', 'PARTO', 'PESHAWAR', 
    'PHNOMPENH', 'PORTAUPRINCE', 'PRAGUE', 'PRETORIA', 'PRISTINA',
    'PORTLOUIS', 'PORTOFSPAIN', u'PODGORICA', u'PORTMORESBY',
    'PARISFR', # Used for US Mission UNESCO, see also UNESCOPARISFR
    'PRAIA', # Found in cable references
    # Q
    'QUITO', 'QUEBEC',
    # R
    'RABAT', 'RANGOON', 'RECIFE', 'REYKJAVIK', 'RIGA', 
    'RIODEJANEIRO', 'RIYADH', 'ROME', 'RPODUBAI', 
    # S 
    'SANAA', 'SANJOSE', 'SANSALVADOR', 'SANTIAGO', 'SANTODOMINGO', 
    'SAOPAULO', 'SARAJEVO', 'SEOUL', 'SHANGHAI', 'SHENYANG', 'SINGAPORE',
    'SKOPJE', 'SOFIA', 'STATE', 'STOCKHOLM', 'STRASBOURG', 'STPETERSBURG',
    'SUVA', 'SAPPORO', 'SECDEF', 'SYDNEY', u'SURABAYA',
    # T
    'TALLINN', 'TASHKENT', 'TAIPEI', 'TBILISI', 'TEGUCIGALPA', 'TEHRAN', 
    'TELAVIV', 'THEHAGUE', 'TIJUANA', 'TOKYO', 'TRIPOLI', 'TUNIS',
    'TORONTO', 'THESSALONIKI', u'TIRANA',
    # U
    'ULAANBAATAR', 'UNVIEVIENNA', 'USNATO', 'USUNNEWYORK', 'USEUBRUSSELS',
    'USOSCE', 'UNROME', u'USTRGENEVA',
    'USDAFAS', # Found in cable references and stands for "U.S. Department of Agriculture"
    'USDOC', # Found in REFerences and stands for "United States Department of Commerce"
    'USCBP', # Found in refs and stands for "U.S. Customs and Border Protection"
    'UNESCOPARISFR', # Same as PARISFR
    # V
    'VATICAN', 'VIENNA', 'VILNIUS', 'VLADIVOSTOK', 'VALLETTA', 'VANCOUVER',
    'VIENTIANE',
    # W
    'WARSAW', 'WELLINGTON', 'WINDHOEK', u'WASHDC',
    # Y
    'YAOUNDE', 'YEREVAN', u'YEKATERINBURG',
    # Z
    'ZAGREB'
)

REFERENCE_ID_PATTERN = re.compile(r'^([0-9]{2})(%s)([0-9]{%d,%d})$' % ('|'.join(_STATIONS), MIN_SERIAL_LENGTH, MAX_SERIAL_LENGTH), re.UNICODE)

# Wrong WikiLeaks cable identifiers
MALFORMED_CABLE_IDS = {
    '08SCTION02OF02SAOPAULO335': u'08SAOPAULO335',
    '09SECTION02OF03QRIPOLI583': u'09TRIPOLI583',
    '08ECTION01OF02MANAMA492': u'08MANAMA492',
}

# Wrong WikiLeaks cable identifiers w/o a valid equivalent
INVALID_CABLE_IDS = {
    # Format:
    # Invalid cable ID: Cable ID which would be correct
    '09EFTOHELSINKI235': u'09HELSINKI235',
    '08SECTION01GF02BISHIEK21': u'08BISHKEK1021', # See <http://aebr.home.xs4all.nl/wl/corrupted/corrupted.html>
    '09SECTION01OF03SANJOSE525': u'09SANJOSE525',
    '07EFTOOTTAWA1217': u'07OTTAWA1217',
    '06BRAILIA1079': u'06BRASILIA1079',
    '07BRASIIA1568': u'07BRASILIA1568',
    '06EFTOSANAA1621': u'06SANAA1621',
    '08EFTOPHNOMPENH416': u'08PHNOMPENH416',
    '09EFTOLONDON2468': u'09LONDON2468',
    '09EFTOLONDON2884': u'09LONDON2884',
    '09EFTOLONDON2858': u'09LONDON2858',
    '08EFTOLONDON2883': u'08LONDON2883',
    '09EFTOLONDON2187': u'09LONDON2187',
    '10EFTOLONDON16': u'10LONDON16',
    '09EFTOLONDON2363': u'09LONDON2363',
    '09EFTOLONDON2618': u'09LONDON2618',
    '09EFTOLONDON2240': u'09LONDON2240',
    '09EFTOLONDON2211': u'09LONDON2211',
    '09EFTOLONDON2521': u'09LONDON2521',
    '09EFTOLONDON2688': u'09LONDON2688',
    '09EFTOLONDON2905': u'09LONDON2905',
    '09EFTOTRIPOLI704': u'09TRIPOLI704',
    '09EFTOLONDON2239': u'09LONDON2239',
    u'09BAU339': u'09BAKU339',
    u'09EFTOSANAA433': u'09SANAA433',
    u'10EFTOKABUL597': u'10KABUL597',
    u'09SECION02OF02NAIROBI417': u'09NAIROBI417',
    u'08AITTAIPIE1698': u'08TAIPEI1698',
    u'07SECTION02OF03EIJING483': u'07BEIJING483',
    u'09COPENHAEN13': u'09COPENHAGEN13',
    u'09EFTOASMARA34': u'09ASMARA34',
    u'06EFTOUSUNNEWYORK1560': u'06USUNNEWYORK1560',
    u'08EFTOJAKARTA2073': u'08JAKARTA2073',
    u'06EFTOANKARA4972': u'06ANKARA4972',
    u'08SECTIN03OF03KABUL3036': u'08KABUL3036',
    u'07EFTOATHENS404': u'07ATHENS404',
    u'06EFTOANKARA5010': u'06ANKARA5010',
    u'10EFTOKABUL668': u'10KABUL668',
    u'06EFTOKABUL5893': u'06KABUL5893',
    u'08EFTODAMASCUS487': u'08DAMASCUS487',
    u'06EFTOANKARA5097': u'06ANKARA5097',
    u'08SECTIO01OF02JERUSALEM1847': u'08JERUSALEM1847',
    u'07SECTION01OF03ANKARA365': u'07ANKARA365',
    u'07EFTOSANAA2300': u'07SANAA2300',
    u'07EFTOSANAA588': u'07SANAA588',
    u'06EFTOPORTMORESBY350': u'06PORTMORESBY350',
    u'07EFTOSANAA588': u'07SANAA588',
    u'09AMEMBASSYHANOI1292': u'09HANOI1292',
    u'06EFTOCARACAS943': u'06CARACAS943',
    u'06EFTOCARACAS2252': u'06CARACAS2252',
    u'07EFTOSANAA784': u'07SANAA784',
    u'06EFTOSANAA1996': u'06SANAA1996',
}
